FROM nginx:alpine

COPY site/index.html /usr/share/nginx/html/index.html
COPY site/assets /usr/share/nginx/html/assets
COPY raw /usr/share/nginx/html/raw
COPY nginx-site.conf /etc/nginx/conf.d/default.conf
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
