server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /raw {
        autoindex on;
        charset utf-8;
        source_charset utf-8;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|apng)$ {
        expires 1M;
        add_header Cache-Control "public, immutable";
    }
}
